### ISSUE TITLE
An error occurred when decoding using the retrained model

### ISSUE THREAD

**Issue by Zmoonzxz** [RenYang-home/OpenDVC#30]
Deer RenYang: 
     Recently, there was an error that bothered me a lot. I retrained a network based on tensorflow-gpu==1.15.0 and tensorflow-compression==1.3, and neither the training process nor the encoding process was abnormal. However, when decoding was performed, the following errors occurred. It showed that I lacked Key MV_synthesis/layer_0/signal_conv2d/bias in checkpoints. I've printed the checkpoints I've taken, and there's no Key MV_synthesis/layer_0/signal_conv2d/bias, Instead, there are some similar MV_synthesis/layer_0/signal_conv2d_4/bias/Adam_2 and MV_synthesis/layer_0/signal_conv2d_4/bias/Adam_4, But I don't know why this is happening. I did not change any code but changed the environment. Can you tell me the reason why this error occurred? By the way, only 280,000 iterations were trained, could this be the cause of the error? Thanks a lot!

     error: `Traceback (most recent call last):
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key MV_synthesis/layer_0/signal_conv2d/bias not found in checkpoint
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key MV_synthesis/layer_0/signal_conv2d/bias not found in checkpoint
         [[node save/RestoreV2 (defined at /home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "OpenDVC_test_video_decoder.py", line 89, in <module>
    saver = tf.train.Saver(max_to_keep=None)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1300, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1618, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OpenDVC_test_video_decoder.py", line 92, in <module>
    saver.restore(sess, save_path=model_path)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1306, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key MV_synthesis/layer_0/signal_conv2d/bias not found in checkpoint
         [[node save/RestoreV2 (defined at /home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "OpenDVC_test_video_decoder.py", line 89, in <module>
    saver = tf.train.Saver(max_to_keep=None)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/ai/anaconda3/envs/tf115/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()`

**Comment by tesf777** [comment]
I also encountered a similar problem, the error report showed that I could not find the key value in the code based on tensorflow-gpu=2.8.0

**Comment by RenYang-home** [comment]
Sorry for the late reply.

It seems that the network has a variable MV_synthesis/layer_0/signal_conv2d/bias, however, your trained model doesn't contain it. In theory this shouldn't happen, since the network should contain the same trainable variables in training and inference. I would recommend you printing out all variable names during both training and inference, and check whether it is missed anywhere.
